name: laundry
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_jsonwebtoken: ^2.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  gcloud: ^0.8.5
  mqtt_client: ^9.6.1
  path_provider: ^2.0.6
  ini: '>=1.0.0'
  test: '>=0.12.0'
  dotenv: ^3.0.0
  flutter_dotenv: ^5.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
